export default [
  // der standard
  {
    title: 'derStandard.at - sport',
    text: 'derStandard.at - sport',
    description: '',
    htmlUrl: 'https://www.derstandard.at/sport',
    xmlUrl: 'https://www.derstandard.at/rss/sport',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['sports'],
  },
  {
    title: 'derStandard.at',
    text: 'derStandard.at',
    description: '',
    htmlUrl: 'https://www.derstandard.at/',
    xmlUrl: 'https://www.derstandard.at/rss',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  // die presse
  {
    title: 'DiePresse.com',
    text: 'DiePresse.com',
    description: '',
    htmlUrl: 'https://www.diepresse.com',
    xmlUrl: 'https://www.diepresse.com/rss/home/',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  {
    title: 'DiePresse.com - wirtschaft',
    text: 'DiePresse.com - wirtschaft',
    description: '',
    htmlUrl: 'https://www.diepresse.com/wirtschaft',
    xmlUrl: 'https://www.diepresse.com/rss/Wirtschaft',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['business'],
  },
  {
    title: 'DiePresse.com - politik',
    text: 'DiePresse.com - politik',
    description: '',
    htmlUrl: 'https://www.diepresse.com/innenpolitik',
    xmlUrl: 'https://www.diepresse.com/rss/Politik',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['politics'],
  },
  {
    title: 'DiePresse.com - kultur',
    text: 'DiePresse.com - kultur',
    description: '',
    htmlUrl: 'https://www.diepresse.com/kultur',
    xmlUrl: 'https://www.diepresse.com/rss/Kultur',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['culture'],
  },
  // orf
  {
    title: 'orf.at',
    text: 'orf.at',
    description: '',
    htmlUrl: 'https://orf.at',
    xmlUrl: 'https://rss.orf.at/news.xml',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  {
    title: 'orf.at - science',
    text: 'orf.at - science',
    description: '',
    htmlUrl: 'https://science.orf.at/',
    xmlUrl: 'https://rss.orf.at/science.xml',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['tech'],
  },
  {
    title: 'orf.at - österreich',
    text: 'orf.at - österreich',
    description: '',
    htmlUrl: 'https://oesterreich.orf.at/',
    xmlUrl: 'https://rss.orf.at/oesterreich.xml',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news', 'regional'],
  },
  {
    title: 'orf.at - sport',
    text: 'orf.at - sport',
    description: '',
    htmlUrl: 'https://sport.orf.at/',
    xmlUrl: 'https://rss.orf.at/sport.xml',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['sports'],
  },
  // krone
  {
    title: 'krone.at',
    text: 'krone.at',
    description: '',
    htmlUrl: 'https://www.krone.at/',
    xmlUrl: 'https://api.krone.at/v1/rss/rssfeed-nachrichten.html',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  {
    title: 'krone.at - sport',
    text: 'krone.at - sport',
    description: '',
    htmlUrl: 'https://www.krone.at/sport',
    xmlUrl: 'https://api.krone.at/v1/rss/rssfeed-sport.html',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['sports'],
  },
  // kurier
  {
    title: 'kurier.at',
    text: 'kurier.at',
    description: '',
    htmlUrl: 'https://kurier.at/',
    xmlUrl: 'https://kurier.at/xml/rss',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  // Salzburger Nachrichten
  {
    title: 'Salzburger Nachrichten',
    text: 'Salzburger Nachrichten',
    description: '',
    htmlUrl: 'https://www.sn.at/',
    xmlUrl: 'https://www.sn.at/xml/rss',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  // oe24
  {
    title: 'oe24',
    text: 'oe24',
    description: '',
    htmlUrl: 'https://www.oe24.at/',
    xmlUrl: 'https://www.oe24.at/xml/rss',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
  {
    title: 'oe24 - Leute',
    text: 'oe24 - Leute',
    description: '',
    htmlUrl: 'https://www.oe24.at/leute',
    xmlUrl: 'https://www.oe24.at/leute/xml/rss',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['people'],
  },
  // APA-OTS RSS Feed
  {
    title: 'APA-OTS',
    text: 'APA-OTS',
    description: '',
    htmlUrl: 'https://www.ots.at/',
    xmlUrl: 'https://www.ots.at/rss/index',
    language: 'de-AT',
    type: 'rss',
    version: 'RSS',
    category: ['news'],
  },
];
