export default [
  // der standard
  {
    type: 'rss',
    text: 'spiegel - leute',
    title: 'spiegel - leute',
    description: '',
    htmlUrl: 'https://www.spiegel.de/panorama/leute/',
    xmlUrl: 'https://www.spiegel.de/panorama/leute/index.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'GQ magazin',
    title: 'GQ magazin',
    description: '',
    htmlUrl: 'https://www.gq-magazin.de/',
    xmlUrl: 'https://www.gq-magazin.de/feed/rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'glamour',
    title: 'glamour',
    description: '',
    htmlUrl: 'https://www.glamour.de',
    xmlUrl: 'https://www.glamour.de/feed/rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'OK!',
    title: 'OK!',
    description: '',
    // https://www.ok-magazin.de/rss/people/rss.xml
    // https://www.ok-magazin.de/people
    htmlUrl: 'https://www.ok-magazin.de',
    xmlUrl: 'https://www.ok-magazin.de/rss.xml',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'ohmymag',
    title: 'ohmymag',
    description: '',
    htmlUrl: 'https://www.ohmymag.de/',
    xmlUrl: 'https://flux.ohmymag.de/rss/open/une.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'vogue germany',
    title: 'vogue germany',
    description: '',
    htmlUrl: 'https://www.vogue.de',
    xmlUrl: 'https://www.vogue.de/feed/rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'wunderweib',
    title: 'wunderweib',
    description: '',
    htmlUrl: 'https://www.wunderweib.de',
    xmlUrl: 'https://flipboard.com/@WunderweibDE.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'bunte',
    title: 'bunte',
    description: '',
    htmlUrl: 'https://www.bunte.de/',
    xmlUrl: 'https://flipboard.com/@BUNTE_DE.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'brigitte',
    title: 'brigitte',
    description: '',
    // https://www.brigitte.de/aktuell/
    // https://www.brigitte.de/aktuell/feed.rss
    htmlUrl: 'https://www.brigitte.de/',
    xmlUrl: 'https://www.brigitte.de/feed.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'klatsch-tratsch',
    title: 'klatsch-tratsch',
    description: '',
    htmlUrl: 'https://www.klatsch-tratsch.de/',
    xmlUrl: 'https://www.klatsch-tratsch.de/feed/',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'jolie - stars',
    title: 'jolie - stars',
    description: '',
    htmlUrl: 'https://www.jolie.de/stars',
    xmlUrl: 'https://www.jolie.de/rss/stars/rss.xml',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'freundin',
    title: 'freundin',
    description: '',
    htmlUrl: 'https://www.freundin.de/',
    xmlUrl: 'https://flipboard.com/@freundin_de.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'gala',
    title: 'gala',
    description: '',
    htmlUrl: 'https://www.gala.de/',
    xmlUrl: 'https://www.gala.de/feed/standard-rss/',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'instyle',
    title: 'instyle',
    description: '',
    htmlUrl: 'https://www.instyle.de/',
    xmlUrl: 'https://flipboard.com/@InStyleGermany.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'elle',
    title: 'elle',
    description: '',
    htmlUrl: 'https://www.elle.de/',
    xmlUrl: 'https://flipboard.com/@ELLE_de.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'watson - stars',
    title: 'watson - stars',
    description: '',
    htmlUrl: 'https://www.watson.de/stars/',
    // https://flipboard.com/@watson_de/stars-entertainment-sq5s4sj3z.rss
    xmlUrl: 'https://www.watson.de/api/2.0/rss/index.xml?tag=Stars',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'promipool',
    title: 'promipool',
    description: '',
    htmlUrl: 'https://www.promipool.de/',
    // xmlUrl: 'https://flipboard.com/@Promipool.rss',
    xmlUrl: 'https://www.promipool.de/websub/feed/latest-news',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
  {
    type: 'rss',
    text: 'cosmopolitan',
    title: 'cosmopolitan',
    description: '',
    htmlUrl: 'https://www.cosmopolitan.de/',
    xmlUrl: 'https://flipboard.com/@CosmopolitanDE.rss',
    language: 'de-DE',
    version: 'RSS2',
    category: ['people'],
  },
];
