export default [
  // der standard
  {
    title: 'derStandard.at - sport',
    text: 'derStandard.at - sport',
    description: '',
    htmlUrl: 'https://www.derstandard.at/sport',
    xmlUrl: 'https://www.derstandard.at/rss/sport',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'derStandard.at - home',
    text: 'derStandard.at - home',
    description: '',
    htmlUrl: 'https://www.derstandard.at/',
    xmlUrl: 'https://www.derstandard.at/rss',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  // die presse
  {
    title: 'DiePresse.com - Home',
    text: 'DiePresse.com - Home',
    description: '',
    htmlUrl: 'https://www.diepresse.com',
    xmlUrl: 'https://www.diepresse.com/rss/home/',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'DiePresse.com - wirtschaft',
    text: 'DiePresse.com - wirtschaft',
    description: '',
    htmlUrl: 'https://www.diepresse.com/wirtschaft',
    xmlUrl: 'https://www.diepresse.com/rss/Wirtschaft',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'DiePresse.com - politik',
    text: 'DiePresse.com - politik',
    description: '',
    htmlUrl: 'https://www.diepresse.com/innenpolitik',
    xmlUrl: 'https://www.diepresse.com/rss/Politik',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'DiePresse.com - kultur',
    text: 'DiePresse.com - kultur',
    description: '',
    htmlUrl: 'https://www.diepresse.com/kultur',
    xmlUrl: 'https://www.diepresse.com/rss/Kultur',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  // orf
  {
    title: 'orf.at',
    text: 'orf.at',
    description: '',
    htmlUrl: 'https://orf.at',
    xmlUrl: 'https://rss.orf.at/news.xml',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'orf.at - science',
    text: 'orf.at - science',
    description: '',
    htmlUrl: 'https://science.orf.at/',
    xmlUrl: 'https://rss.orf.at/science.xml',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'orf.at - österreich',
    text: 'orf.at - österreich',
    description: '',
    htmlUrl: 'https://oesterreich.orf.at/',
    xmlUrl: 'https://rss.orf.at/oesterreich.xml',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'orf.at - sport',
    text: 'orf.at - sport',
    description: '',
    htmlUrl: 'https://sport.orf.at/',
    xmlUrl: 'https://rss.orf.at/sport.xml',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  // krone
  {
    title: 'krone.at',
    text: 'krone.at',
    description: '',
    htmlUrl: 'https://www.krone.at/',
    xmlUrl: 'https://api.krone.at/v1/rss/rssfeed-nachrichten.html',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  {
    title: 'krone.at - sport',
    text: 'krone.at - sport',
    description: '',
    htmlUrl: 'https://www.krone.at/sport',
    xmlUrl: 'https://api.krone.at/v1/rss/rssfeed-sport.html',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
  // kurier
  {
    title: 'kurier.at',
    text: 'kurier.at',
    description: '',
    htmlUrl: 'https://kurier.at/',
    xmlUrl: 'https://kurier.at/xml/rss',
    language: 'AT',
    type: 'rss',
    version: 'RSS',
    category: [],
  },
];
